const data = {
  global: {
    "lecturer(speaker)": "Lecturer (speaker)",
    academyAdministrator: "Academy Administrator",
    acceptedByMember: "Accepted by member",
    additionalStatus: "Additional status",
    administrator: "Administrator",
    allowTestsForEveryone: "Allow tests for everyone",
    answer: "Answer",
    apply: "Apply",
    apr: "Apr",
    areaOfResponsibility: "Area of responsibility",
    attachFiles: "Attach files",
    attachImages: "Attach images",
    aug: "Aug",
    author: "Author",
    availability: "Availability",
    avatar: "Avatar",
    awaiting: "Awaiting",
    block: "Block",
    buy: "Buy",
    canCreateWebinars: "Can create webinars",
    channel: "Channel",
    clientWithoutDMS: "Client without DMS",
    close: "close",
    clubSKPLevel: "Club SKP Level",
    comment: "Comment",
    confirm: "Confirm",
    countryOfRegistration: "Country of registration",
    creator: "Creator",
    crmManager: "CRM manager",
    dateAndTime: "date and time",
    dateOfRegistration: "Date of registration",
    dateOfTheFirst: "Date of the first workshop",
    dec: "Dec",
    dependentSeminars: "Dependent Seminars",
    detailedInformation: "detailed information",
    didNotHave: "Did not have",
    download: "Download",
    duration: "Duration",
    entity: "Entity",
    expirationDate: "expiration date",
    externalRoles: "External roles",
    feb: "Feb",
    file: "File",
    filters: "Filters",
    further: "Further",
    graduates: "Graduates",
    headOfRegionEducation: "Head of region education",
    headOfSales: "Head of sales",
    hide: "Hide",
    highlight: "highlight",
    image: "Image",
    inactive: "Inactive",
    individuals: "Individuals",
    indolaLoyaltyLevel: "Indola Loyalty Level",
    internalRoles: "Internal Roles",
    isCopyright: "Is copyright",
    jan: "Jan",
    july: "July",
    june: "June",
    limitedAccess: "Limited access",
    linkToVimeo: "link to vimeo",
    location: "Location",
    mail: "Mail",
    mar: "Mar",
    may: "May",
    mediaFiles: "media files",
    middleName: "Middle name",
    more: "More",
    name: "Name",
    ncaThreshold: "NCA Threshold",
    nomination: "Nomination",
    nov: "Nov",
    oct: "Oct",
    order: "Order",
    passedSeminars: "Passed seminars",
    phoneFormat: "Phone format",
    question: "Question",
    questionsAndAnswers: "Questions and answers",
    regionByApplication: "Region by application",
    reject: "Reject",
    rejected: "Rejected",
    resetAll: "Reset all",
    responsiblePersons: "Responsible persons",
    responsibleSalesRepresentative: "Responsible Sales Representative",
    responsibleSupervisor: "Responsible Supervisor",
    role: "Role",
    roles: "Roles",
    salesRepresentetive: "Sales representetive",
    salonAdministrator: "Salon administrator",
    salonName: "Salon name",
    seminar: "Seminar",
    seminarTitle: "Seminar title",
    seminarsCompleted: "Seminars completed",
    sen: "Sen",
    service: "Service",
    shipmentMonth: "Shipment month",
    signUp: "Sign up",
    sorting: "Sorting",
    start: "Start",
    submitYourApplication: "Submit your application",
    successfulBlocking: "Successful blocking",
    successfulChange: "Successful change",
    successfulConfirmation: "Successful confirmation",
    successfulUnlock: "Successful unlock",
    superAdmin: "super admin",
    surname: "Surname",
    teacher: "Teacher",
    text: "Text",
    theDate: "the date",
    theEnding: "The ending",
    theLocalTime: "The local time",
    timezone: "Timezone",
    toAccept: "To accept",
    tradePoint: "Trade point",
    tradeTurnover: "Trade turnover",
    trainingLeader: "Training leader",
    unlock: "Unlock",
    venueAddress: "Venue address",
    version: "Version",
    video: "Video",
    virtual: "Virtual",
    // our translates
    "interEmail...": "Enter email addresses ...",
    "interPhone...": "Enter phones ...",
    academies: "Academy",
    academy: "Academy",
    academyAdministrators: "Administrators of the Academies",
    acceptedByTheParticipant: "Accepted by the participant",
    additionalInformation: "Additional Information",
    address: "Address",
    administrativeDays: "Administrative days",
    administratorsOfTheAcademies: "Administrators of the Academies",
    applications: "Applications",
    applicationsForTheSeminar: "Applications for the seminar",
    art: "Art",
    attachTheImages: "Attach the images",
    belarus: "Belarus",
    brand: "Brand",
    broadcasts: "Broadcasts",
    businessConsultant: "Business consultant",
    businessTrainings: "Business Trainings",
    calendar: "Calendar",
    cancelTheSeminar: "Cancel the seminar",
    cancelTheWebinar: "Cancel the webinar",
    catalogTemplate: "Catalog template",
    catalogVideo: "Catalog video",
    categoriesOfMedia: "Categories of media",
    categoriesOfTemplates: "Categories of templates",
    categoriesOfVideo: "Categories of video",
    category: "Category",
    chooseAcademy: "Select the academy",
    chooseBrand: "Select the brand",
    chooseTheCity: "Choose the city",
    chooseTheRole: "Choose the role",
    choosingUsersOfThese: "Choosing users of these roles",
    cities: "Cities",
    city: "City",
    clientWithoutVHI: "Client without VHI",
    clients: "Clients",
    clientsWithoutVHI: "Clients without VHI",
    completionOfVoting: "Completion of voting",
    confirmThePassword: "Confirm the password",
    countries: "Countries",
    country: "Country",
    createAnInformationNewsletter: "Create an information newsletter",
    createdBy: "Creator",
    crm: "CRM",
    date: "the date",
    dateOfFirstShipment: "Date of first shipment",
    datePlusTime: "Date + Time",
    dateRange: "Date range",
    dates: "Dates",
    deleteAWebinar: "Delete a webinar",
    deleteTheDay: "Delete the day",
    deleteTheElement: "Delete the element",
    deleteTheSeminar: "Delete the seminar",
    description: "Description",
    discountsFromPartners: "Discounts from partners",
    durationPerMin: "Duration (min)",
    editASeminar: "Edit a seminar",
    editTheUser: "Edit the user",
    educationTeam: "Teaching team",
    employees: "Employees",
    errors: "Errors",
    faq: "FAQ",
    farEast: "Far East",
    fullName: "Full name",
    goToEditing: "Go to editing",
    group: "Group",
    headOfEducation: "The head of training is deleted",
    headOfRegions: "Regions heads",
    headOfTheRegion: "Head of the region of training",
    headOfTheRegionLearn: "Head of the region of training",
    headOfTraining: "Head of training",
    header: "Header",
    headsOfSales: "Sales managers",
    hitek: "Hitek",
    information: "Information",
    informationNewsletter: "Information newsletter",
    integration: "Integration",
    inviteParticipants: "Invite participants",
    inviteStylists: "Invite stylists",
    invitedSalons: "Invited salons",
    itCanCreateWebinars: "It can create webinars",
    itIsCopyright: "It is copyright",
    kyrgyzstan: "Kyrgyzstan",
    lasting: "Lasting",
    lecturer: "Lecturer (Speaker)",
    legalDocuments: "Legal documents",
    level: "Level",
    levelIndolaLoyalty: "Level Indola Loyalty",
    link: "Link",
    marketingManagers: "Marketing Managers",
    message: "Message",
    messageText: "Message text",
    metro: "Underground",
    metroStation: "Metro station",
    mix: "Mix",
    month: "Month",
    monthOfShipment: "Month of shipment",
    moscow: "Moscow",
    moscowRegionAndCenter: "Moscow region and center",
    noTranslation: "no translation",
    northWestAndTheRepublicOfBelarus: "North-West and the Republic of Belarus",
    oneDate: "OneDate",
    openSorting: "Open the sorting",
    orderHistory: "purchase history",
    outlet: "Outlet",
    outlets: "Outlets",
    ownersOfSalons: "Owners of salons",
    participants: "Participants",
    passedTests: "Passed tests",
    password: "Password",
    passwordConfirm: "Confirm the password",
    periodOfRegistration: "Registration period",
    personalArea: "Personal Area",
    phones: "Phones",
    price: "Price",
    program: "Program",
    quantity: "Quantity",
    quarter: "Quarter",
    range: "Range",
    readMore: "Read more",
    recipients: "Recipients",
    region: "Region",
    regionOnRequest: "Region on request",
    regions: "Regions",
    regionsHeads: "Regions heads",
    regionsOfEducation: "Regions of training",
    regionsOfTraining: "Regions of training",
    resetEverything: "Reset everything",
    resolutionOfTestsTo: "Resolution of tests to all",
    responsible: "Responsible",
    responsiblePerson: "Responsible person",
    responsibleSt: "Responsible St.",
    responsibleTP: "Responsible TP",
    responsibleTradingRepresentative: "Responsible trading representative",
    rr: "Pr",
    rro: "RRO",
    russiaKazakhstan: "Russia, Kazakhstan",
    salesManager: "Sales manager",
    salesManagers: "Sales managers",
    salesRepresentative: "Sales Representative",
    salesRepresentatives: "Trading representatives",
    salon: "Salon",
    salonAdministrators: "Salon administrators",
    salonEmployees: "Salon employees",
    salonOwners: "Owners of salons",
    salons: "Salons",
    salonsCount: "Salons",
    sample: "Sample",
    score: "Score",
    search: "Search",
    selectTheSalons: "Select the salons",
    seminarCatalog: "Seminar catalog",
    seminarTemplates: "Seminar templates",
    seminars: "Seminars",
    seminarsPassed: "Seminars passed",
    sep: "Saint",
    settings: "Settings",
    settlements: "Settlements",
    shipment: "Shipment",
    showFilters: "Show filters",
    siberia: "Siberia",
    siteAdministrators: "Site administrators",
    status: "Status",
    stylists: "Stylists",
    stylistsCount: "Stylists",
    superAdministrator: "Super administrator",
    supervisor1: "Supervisor1",
    supervisor: "Supervisor",
    supervisorTechnologists: "Supervisor technologists",
    supervisors: "Supervisers",
    surnames: "Surnames",
    target: "Target",
    teachers: "Teachers",
    techno: "Techno",
    technologist: "Technologist",
    technologistSupervisors: "Supervisors of technologists",
    technologists: "Techno",
    telephone: "Telephone",
    templateCatalogs: "Categories of templates",
    templateCategories: "Categories of templates",
    temporaryPage: "Temporary page",
    temporaryZone: "Temporary zone",
    testManagement: "Test management",
    tests: "Tests",
    theAddressOfThe: "The address of the conduct",
    theAreaOfResponsibility: "The area of responsibility",
    theBeginningOfThe: "The beginning of the broadcast",
    theChoiceOfRoles: "The choice of roles",
    theCountryOfRegistration: "The country of registration",
    theDateOfThe: "the date of the beginning",
    theDateOfTheFirstSeminar: "The date of the first seminar",
    theHeadOfThe: "The head of the region",
    theNameOfThe: "The name of the address",
    theNameOfTheSalon: "The name of the salon",
    theOwnerOfThe: "The owner of the salon",
    thePlayerCode: "The player code",
    theRegionOfTraining: "The region of training",
    theShops: "The shops",
    title: "Name",
    topics: "Topics",
    trainingRegion: "The region of training",
    turnover: "Turnover",
    type: "Type of",
    typeOf: "Type of",
    unique: "Unique",
    ural: "Ural",
    users: "Users",
    videoCategories: "Categories of video",
    waiting: "Waiting",
    warmId: "Warm ID",
    webinar: "Webinar",
    webinarCalendar: "Webinar calendar",
    webinarParticipants: "Participants in webinars",
    webinars: "Webinars",
    webinarsTemplates: "Webinars templates",
    worksRHDA: "RHDA work",
    year: "Year",
    zoneOfResponsibility: "Zone of responsibility",
  }
};

module.exports = data.global;
