const data = {
  global: {
    academyAdministrator: "Academy Administrator",
    acceptedByMember: "Accepted by member",
    additionalStatus: "Additional status",
    administrator: "Administrator",
    allowTestsForEveryone: "Allow tests for everyone",
    answer: "Answer",
    apply: "Apply",
    apr: "Apr",
    areaOfResponsibility: "Area of responsibility",
    attachFiles: "Attach files",
    attachImages: "Attach images",
    aug: "Aug",
    author: "Author",
    availability: "Availability",
    avatar: "Avatar",
    awaiting: "Awaiting",
    block: "Block",
    buy: "Buy",
    canCreateWebinars: "Can create webinars",
    channel: "Channel",
    clientWithoutDMS: "Client without DMS",
    close: "close",
    clubSKPLevel: "Club SKP Level",
    comment: "Comment",
    confirm: "Confirm",
    countryOfRegistration: "Country of registration",
    creator: "Creator",
    crmManager: "CRM manager",
    dateAndTime: "date and time",
    dateOfRegistration: "Date of registration",
    dateOfTheFirst: "Date of the first workshop",
    dec: "Dec",
    dependentSeminars: "Dependent Seminars",
    detailedInformation: "detailed information",
    didNotHave: "Did not have",
    download: "Download",
    duration: "Duration",
    "duration(min)": "Duration (min)",
    entity: "Entity",
    expirationDate: "expiration date",
    externalRoles: "External roles",
    feb: "Feb",
    file: "File",
    filters: "Filters",
    further: "Further",
    graduates: "Graduates",
    headOfRegionEducation: "Head of region education",
    headOfSales: "Head of sales",
    hide: "Hide",
    highlight: "highlight",
    image: "Image",
    inactive: "Inactive",
    individuals: "Individuals",
    indolaLoyaltyLevel: "Indola Loyalty Level",
    internalRoles: "Internal Roles",
    isCopyright: "Is copyright",
    jan: "Jan",
    july: "July",
    june: "June",
    "lecturer(speaker)": "Lecturer (speaker)",
    limitedAccess: "Limited access",
    linkToVimeo: "link to vimeo",
    location: "Location",
    mail: "Mail",
    mar: "Mar",
    may: "May",
    mediaFiles: "media files",
    middleName: "Middle name",
    more: "More",
    name: "Name",
    ncaThreshold: "NCA Threshold",
    nomination: "Nomination",
    nov: "Nov",
    oct: "Oct",
    order: "Order",
    passedSeminars: "Passed seminars",
    phoneFormat: "Phone format",
    question: "Question",
    questionsAndAnswers: "Questions and answers",
    regionByApplication: "Region by application",
    reject: "Reject",
    rejected: "Rejected",
    resetAll: "Reset all",
    responsiblePersons: "Responsible persons",
    responsibleSalesRepresentative: "Responsible Sales Representative",
    responsibleSupervisor: "Responsible Supervisor",
    role: "Role",
    roles: "Roles",
    salesRepresentetive: "Sales representetive",
    salonAdministrator: "Salon administrator",
    salonName: "Salon name",
    seminar: "Seminar",
    seminarTitle: "Seminar title",
    seminarsCompleted: "Seminars completed",
    sen: "Sen",
    service: "Service",
    shipmentMonth: "Shipment month",
    signUp: "Sign up",
    sorting: "Sorting",
    start: "Start",
    submitYourApplication: "Submit your application",
    successfulBlocking: "Successful blocking",
    successfulChange: "Successful change",
    successfulConfirmation: "Successful confirmation",
    successfulUnlock: "Successful unlock",
    superAdmin: "super admin",
    surname: "Surname",
    teacher: "Teacher",
    text: "Text",
    theDate: "the date",
    theEnding: "The ending",
    theLocalTime: "The local time",
    timezone: "Timezone",
    toAccept: "To accept",
    tradePoint: "Trade point",
    tradeTurnover: "Trade turnover",
    trainingLeader: "Training leader",
    unlock: "Unlock",
    venueAddress: "Venue address",
    version: "Version",
    video: "Video",
    virtual: "Virtual",
  },
};

export default data;
