const data = {
  global: {
    "lecturer(speaker)": "Преподаватель (спикер)",
    academyAdministrator: "Администратор Академии",
    acceptedByMember: "Принято участником",
    additionalStatus: "Доп.статус",
    administrator: "Администратор",
    allowTestsForEveryone: "Разрешение тестов всем",
    answer: "Ответ",
    apply: "Применить",
    apr: "Апр",
    areaOfResponsibility: "Зона ответственности",
    attachFiles: "Прикрепите файлы",
    attachImages: "Прикрепите изображения",
    aug: "Авг",
    author: "Автор",
    availability: "Доступность",
    avatar: "Аватар",
    awaiting: "Ожидает",
    block: "Блокировать",
    buy: "Купить",
    canCreateWebinars: "Может создавать вебинары",
    channel: "Канал",
    clientWithoutDMS: "Клиент без ДМС",
    close: "Закрыть",
    clubSKPLevel: "Уровень Club SKP",
    comment: "Комментарий",
    confirm: "Подтвердить",
    countryOfRegistration: "Страна регистрации",
    creator: "Создатель",
    crmManager: "CRM-менеджер",
    dateAndTime: "Дата и время",
    dateOfRegistration: "Дата регистрации",
    dateOfTheFirst: "Дата первого семинара",
    dec: "Дек",
    dependentSeminars: "Зависимые семинары",
    detailedInformation: "Подробная информация",
    didNotHave: "Не было",
    download: "Скачать",
    duration: "Длительность",
    entity: "Юридическое лицо",
    expirationDate: "Дата окончания",
    externalRoles: "Внешние роли",
    feb: "Фев",
    file: "Файл",
    filters: "Фильтры",
    further: "Далее",
    graduates: "Выпускники",
    headOfRegionEducation: "Руководитель региона обучения",
    headOfSales: "Руководитель продаж",
    hide: "Скрыть",
    highlight: "Подсветить",
    image: "Изображение",
    inactive: "Неактивный",
    individuals: "Индивидуалы",
    indolaLoyaltyLevel: "Уровень Indola Loyalty",
    internalRoles: "Внутренние роли",
    isCopyright: "Является авторским",
    jan: "Янв",
    july: "Июль",
    june: "Июнь",
    limitedAccess: "Ограниченный доступ",
    linkToVimeo: "Ссылка на vimeo",
    location: "Место проведения",
    mail: "Почта",
    mar: "Мар",
    may: "Май",
    mediaFiles: "Медиа-файлы",
    middleName: "Отчество",
    more: "Подробнее",
    name: "Имя",
    ncaThreshold: "Порог NCA",
    nomination: "Номинация",
    nov: "Ноя",
    oct: "Окт",
    order: "Порядок",
    passedSeminars: "Пройденных семинаров",
    phoneFormat: "Формат телефона",
    question: "Вопрос",
    questionsAndAnswers: "Вопросы и ответы",
    regionByApplication: "Регион по заявкам",
    reject: "Отклонить",
    rejected: "Отклонено",
    resetAll: "Сбросить все",
    responsiblePersons: "Ответственные лица",
    responsibleSalesRepresentative: "Ответственный Торговый представитель",
    responsibleSupervisor: "Ответственный Супервизор",
    role: "Роль",
    roles: "Роли",
    salesRepresentetive: "Бизнес консультант",
    salonAdministrator: "Администратор салона",
    salonName: "Название салона",
    seminar: "Семинар",
    seminarTitle: "Название семинара",
    seminarsCompleted: "Пройдено семинаров",
    sen: "Сен",
    service: "Услуга",
    shipmentMonth: "Месяц отгрузки",
    signUp: "Записаться",
    sorting: "Сортировка",
    start: "Начало",
    submitYourApplication: "Оставить заявку",
    successfulBlocking: "Успешная блокировка",
    successfulChange: "Успешное изменение",
    successfulConfirmation: "Успешное подтверждение",
    successfulUnlock: "Успешная разблокировка",
    superAdmin: "Суперадминистратор",
    surname: "Фамилия",
    teacher: "Преподаватель",
    text: "Текст",
    theDate: "Дата",
    theEnding: "Окончание",
    theLocalTime: "Местное время",
    timezone: "Часовой пояс",
    toAccept: "Принять",
    tradePoint: "Торговая точка",
    tradeTurnover: "Товарооборот",
    trainingLeader: "Тренинг-лидер",
    unlock: "Разблокировать",
    venueAddress: "Адрес проведения",
    version: "Версия",
    video: "Видео",
    virtual: "Виртуальная",
    // our translates
    "interEmail...": "Введите email адреса...",
    "interPhone...": "Введите телефоны...",
    academies: "Академии",
    academy: "Академия",
    academyAdministrators: "Администраторы академий",
    acceptedByTheParticipant: "Принято участником",
    additionalInformation: "Дополнительная информация",
    address: "Адрес",
    administrativeDays: "Административные дни",
    administratorsOfTheAcademies: "Администраторы академий",
    applications: "Заявки",
    applicationsForTheSeminar: "Заявки на семинар",
    art: "СТ",
    attachTheImages: "Прикрепите изображения",
    belarus: "Беларусь",
    brand: "Бренд",
    broadcasts: "Трансляции",
    businessConsultant: "Бизнес консультант",
    businessTrainings: "Бизнес тренинги",
    calendar: "Календарь",
    cancelTheSeminar: "Отменить семинар",
    cancelTheWebinar: "Отменить вебинар",
    catalogTemplate: "Шаблон каталога",
    catalogVideo: "Каталог видео",
    categoriesOfMedia: "Категории медиа",
    categoriesOfTemplates: "Категории шаблонов",
    categoriesOfVideo: "Категории видео",
    category: "Категория",
    chooseAcademy: "Выберите академии",
    chooseBrand: "Выберите бренд",
    chooseTheCity: "Выберите город",
    chooseTheRole: "Выберите роль",
    choosingUsersOfThese: "Выбор пользователей данных ролей",
    cities: "Города",
    city: "Город",
    clientWithoutVHI: "Клиент без ДМС",
    clients: "Клиенты",
    clientsWithoutVHI: "Клиенты без ДМС",
    completionOfVoting: "Завершение голосования",
    confirmThePassword: "Подтвердите пароль",
    countries: "Страны",
    country: "Страна",
    createAnInformationNewsletter: "Создать информационную рассылку",
    createdBy: "Создатель",
    crm: "CRM",
    date: "Дата",
    dateOfFirstShipment: "Дата первой отгрузки",
    datePlusTime: "Дата + время",
    dateRange: "Диапазон дат",
    dates: "Даты проведения",
    deleteAWebinar: "Удалить вебинар",
    deleteTheDay: "Удалить день",
    deleteTheElement: "Удалить элемент",
    deleteTheSeminar: "Удалить семинар",
    description: "Описание",
    discountsFromPartners: "Скидки от партнеров",
    durationPerMin: "Продолжительность (мин)",
    editASeminar: "Редактировать семинар",
    editTheUser: "Редактировать пользователя",
    educationTeam: "Команда обучения",
    employees: "Сотрудники",
    errors: "Ошибки",
    faq: "FAQ",
    farEast: "Дальний Восток",
    fullName: "ФИО",
    goToEditing: "Перейти к редактированию",
    group: "Группа",
    headOfEducation: "Руководитель обучения удален",
    headOfRegions: "Руководители регионов",
    headOfTheRegion: "Руководитель региона обучения",
    headOfTheRegionLearn: "Руководитель региона обучения",
    headOfTraining: "Руководитель обучения",
    header: "Заголовок",
    headsOfSales: "Руководители продаж",
    hitek: "Хитэк",
    information: "Информация",
    informationNewsletter: "Информационная рассылка",
    integration: "Интеграция",
    inviteParticipants: "Пригласить участников",
    inviteStylists: "Пригласить стилистов",
    invitedSalons: "Приглашенные салоны",
    itCanCreateWebinars: "Может создавать вебинары",
    itIsCopyright: "Является авторским",
    kyrgyzstan: "Киргизия",
    lasting: "Продолжительность",
    lecturer: "Преподаватель (спикер)",
    legalDocuments: "Правовые документы",
    level: "Уровень",
    levelIndolaLoyalty: "Уровень Indola Loyalty",
    link: "Ссылка",
    marketingManagers: "Маркетинг менеджеры",
    message: "Сообщение",
    messageText: "Текст сообщения",
    metro: "Метро",
    metroStation: "Станция метро",
    mix: "MIX",
    month: "Месяц",
    monthOfShipment: "Месяц отгрузки",
    moscow: "Москва",
    moscowRegionAndCenter: "Московская область и Центр",
    noTranslation: "нет перевода",
    northWestAndTheRepublicOfBelarus: "Северо-Запад и Республики Беларусь",
    oneDate: "Одна дата",
    openSorting: "Открыть сортировку",
    orderHistory: "История заказов",
    outlet: "Торговая точка",
    outlets: "Торговые точки",
    ownersOfSalons: "Владельцы салонов",
    participants: "Участники",
    passedTests: "Пройденные тесты",
    password: "Пароль",
    passwordConfirm: "Подтвердите пароль",
    periodOfRegistration: "Период регистрации",
    personalArea: "Личный кабинет",
    phones: "Телефоны",
    price: "Цена",
    program: "Программа",
    quantity: "Количество",
    quarter: "Квартал",
    range: "Диапазон",
    readMore: "Подробнее",
    recipients: "Получатели",
    region: "Регион",
    regionOnRequest: "Регион по заявкам",
    regions: "Регионы",
    regionsHeads: "Руководители регионов",
    regionsOfEducation: "Регионы обучения",
    regionsOfTraining: "Регионы обучения",
    resetEverything: "Сбросить все",
    resolutionOfTestsTo: "Разрешение тестов всем",
    responsible: "Ответственный",
    responsiblePerson: "Ответственное лицо",
    responsibleSt: "Ответственный СВ",
    responsibleTP: "Ответственный ТП",
    responsibleTradingRepresentative: "Ответственный Торговый представитель",
    rr: "РР",
    rro: "РРО",
    russiaKazakhstan: "Россия, Казахстан",
    salesManager: "Руководитель продаж",
    salesManagers: "Руководители продаж",
    salesRepresentative: "Торговый представитель",
    salesRepresentatives: "Торговые представители",
    salon: "Салон",
    salonAdministrators: "Администраторы салонов",
    salonEmployees: "Сотрудники салонов",
    salonOwners: "Владельцы салонов",
    salons: "Салоны",
    salonsCount: "Салонов",
    sample: "Шаблон",
    score: "Магазин",
    search: "Поиск",
    selectTheSalons: "Выберите салоны",
    seminarCatalog: "Каталог семинаров",
    seminarTemplates: "Шаблоны семинаров",
    seminars: "Семинары",
    seminarsPassed: "Пройдено семинаров",
    sep: "Сен",
    settings: "Настройки",
    settlements: "Населенные пункты",
    shipment: "Отгрузка",
    showFilters: "Показать фильтры",
    siberia: "Сибирь",
    siteAdministrators: "Администраторы сайта",
    status: "Статус",
    stylists: "Стилисты",
    stylistsCount: "Стилистов",
    superAdministrator: "Суперадминистратор",
    supervisor1: "Супервайзер1",
    supervisor: "Супервайзер",
    supervisorTechnologists: "Супервайзер технологов",
    supervisors: "Супервайзеры",
    surnames: "Фамилии",
    target: "Цель",
    teachers: "Преподаватели",
    techno: "Технологи",
    technologist: "Технолог",
    technologistSupervisors: "Супервайзеры технологов",
    technologists: "Технологи",
    telephone: "Телефон",
    templateCatalogs: "Категории шаблонов",
    templateCategories: "Категории шаблонов",
    temporaryPage: "Временная страница",
    temporaryZone: "Временная зона",
    testManagement: "Управление тестами",
    tests: "Тесты",
    theAddressOfThe: "Адрес проведения",
    theAreaOfResponsibility: "Зона ответствености",
    theBeginningOfThe: "Начало трансляции",
    theChoiceOfRoles: "Выбор ролей",
    theCountryOfRegistration: "Страна регистрации",
    theDateOfThe: "Дата начала",
    theDateOfTheFirstSeminar: "Дата первого семинара",
    theHeadOfThe: "Руководитель региона",
    theNameOfThe: "Название адреса",
    theNameOfTheSalon: "Название салона",
    theOwnerOfThe: "Владелец салона",
    thePlayerCode: "Код плеера",
    theRegionOfTraining: "Регион обучения",
    theShops: "Магазины",
    title: "Название",
    topics: "Темы",
    trainingRegion: "Регион обучения",
    turnover: "Товарооборот",
    type: "Тип",
    typeOf: "Тип",
    unique: "Уникальных",
    ural: "Урал",
    users: "Пользователи",
    videoCategories: "Категории видео",
    waiting: "Ожидает",
    warmId: "WARM ID",
    webinar: "Вебинар",
    webinarCalendar: "Календарь вебинаров",
    webinarParticipants: "Участники вебинаров",
    webinars: "Вебинары",
    webinarsTemplates: "Шаблоны вебинаров",
    worksRHDA: "Работы RHDA",
    year: "Год",
    zoneOfResponsibility: "Зона ответственности",
  }
};

module.exports = data.global;
