const data = {
  global: {
    "duration(min)": "Продолжительность (мин)",
    "lecturer(speaker)": "Преподаватель (спикер)",
    'interEmail...': 'Введите email адреса...',
    'interPhone...': 'Введите телефоны...',
    academies: 'Академии',
    academy: 'Академия',
    academyAdministrator: "Администратор Академии",
    academyAdministrators: 'Администраторы академий',
    acceptedByMember: "Принято участником",
    acceptedByTheParticipant: 'Принято участником',
    additionalInformation: "Дополнительная информация",
    additionalStatus: "Доп.статус",
    address: "Адрес",
    administrator: "Администратор",
    administratorsOfTheAcademies: "Администраторы академий",
    allowTestsForEveryone: "Разрешение тестов всем",
    answer: "Ответ",
    applications: 'Заявки',
    apply: "Применить",
    apr: "Апр",
    areaOfResponsibility: "Зона ответственности",
    art: "СТ",
    attachFiles: "Прикрепите файлы",
    attachImages: "Прикрепите изображения",
    attachTheImages: 'Прикрепите изображения',
    aug: "Авг",
    author: "Автор",
    availability: "Доступность",
    avatar: "Аватар",
    awaiting: "Ожидает",
    belarus: "Беларусь",
    block: "Блокировать",
    brand: 'Бренд',
    broadcasts: 'Трансляции',
    businessConsultant: 'Бизнес консультант',
    businessTrainings: "Бизнес тренинги",
    buy: "Купить",
    canCreateWebinars: "Может создавать вебинары",
    cancelTheSeminar: "Отменить семинар",
    catalogTemplate: "Шаблон каталога",
    categoriesOfMedia: 'Категории медиа',
    categoriesOfTemplates: "Категории шаблонов",
    categoriesOfVideo: "Категории видео",
    category: "Категория",
    channel: "Канал",
    chooseAcademy: 'Выберите академии',
    chooseBrand: 'Выберите бренд',
    chooseTheCity: "Выберите город",
    chooseTheRole: "Выберите роль",
    choosingUsersOfThese: "Выбор пользователей данных ролей",
    cities: 'Города',
    city: "Город",
    clientWithoutDMS: "Клиент без ДМС",
    clientWithoutVHI: 'Клиент без ДМС',
    clients: 'Клиенты',
    clientsWithoutVHI: "Клиенты без ДМС",
    close: "Закрыть",
    clubSKPLevel: "Уровень Club SKP",
    comment: "Комментарий",
    completionOfVoting: "Завершение голосования",
    confirm: "Подтвердить",
    confirmThePassword: "Подтвердите пароль",
    countries: 'Страны',
    country: 'Страна',
    countryOfRegistration: "Страна регистрации",
    createAnInformationNewsletter: "Создать информационную рассылку",
    createdBy: "Создатель",
    creator: "Создатель",
    crm: "CRM",
    crmManager: "CRM-менеджер",
    date: 'Дата',
    dateAndTime: "Дата и время",
    dateOfRegistration: "Дата регистрации",
    dateOfTheFirst: "Дата первого семинара",
    datePlusTime: "Дата + время",
    dateRange: "Диапазон дат",
    dates: "Даты проведения",
    dec: "Дек",
    deleteTheDay: "Удалить день",
    deleteTheElement: "Удалить элемент",
    deleteTheSeminar: "Удалить семинар",
    dependentSeminars: "Зависимые семинары",
    description: "Описание",
    detailedInformation: "Подробная информация",
    didNotHave: "Не было",
    download: "Скачать",
    duration: "Длительность",
    durationPerMin: 'Продолжительность (мин)',
    editASeminar: "Редактировать семинар",
    editTheUser: "Редактировать пользователя",
    educationTeam: 'Команда обучения',
    employees: 'Сотрудники',
    entity: "Юридическое лицо",
    expirationDate: "Дата окончания",
    externalRoles: "Внешние роли",
    faq: 'FAQ',
    farEast: "Дальний Восток",
    feb: "Фев",
    file: "Файл",
    filters: "Фильтры",
    fullName: 'ФИО',
    further: "Далее",
    graduates: "Выпускники",
    group: 'Группа',
    headOfEducation: 'Руководитель обучения удален',
    headOfRegionEducation: "Руководитель региона обучения",
    headOfRegions: 'Руководители регионов',
    headOfSales: "Руководитель продаж",
    headOfTheRegion: 'Руководитель региона обучения',
    headOfTheRegionLearn: 'Руководитель региона обучения',
    headsOfSales: 'Руководители продаж',
    hide: "Скрыть",
    highlight: "Подсветить",
    image: "Изображение",
    inactive: "Неактивный",
    individuals: "Индивидуалы",
    indolaLoyaltyLevel: "Уровень Indola Loyalty",
    information: 'Информация',
    informationNewsletter: "Информационная рассылка",
    integration: 'Интеграция',
    internalRoles: "Внутренние роли",
    inviteStylists: "Пригласить стилистов",
    invitedSalons: "Приглашенные салоны",
    isCopyright: "Является авторским",
    itCanCreateWebinars: 'Может создавать вебинары',
    itIsCopyright: 'Является авторским',
    jan: "Янв",
    july: "Июль",
    june: "Июнь",
    kyrgyzstan: "Киргизия",
    lecturer: 'Преподаватель (спикер)',
    level: "Уровень",
    levelIndolaLoyalty: 'Уровень Indola Loyalty',
    limitedAccess: "Ограниченный доступ",
    link: "Ссылка",
    linkToVimeo: "Ссылка на vimeo",
    location: "Место проведения",
    mail: "Почта",
    mar: "Мар",
    marketingManagers: 'Маркетинг менеджеры',
    may: "Май",
    mediaFiles: "Медиа-файлы",
    message: "Сообщение",
    messageText: "Текст сообщения",
    metro: 'Метро',
    metroStation: "Станция метро",
    middleName: "Отчество",
    mix: 'MIX',
    month: "Месяц",
    monthOfShipment: 'Месяц отгрузки',
    more: "Подробнее",
    moscow: "Москва",
    moscowRegionAndCenter: "Московская область и Центр",
    name: "Имя",
    ncaThreshold: "Порог NCA",
    noTranslation: "нет перевода",
    nomination: "Номинация",
    northWestAndTheRepublicOfBelarus: "Северо-Запад и Республики Беларусь",
    nov: "Ноя",
    oct: "Окт",
    oneDate: "oneDate",
    openSorting: 'Открыть сортировку',
    order: "Порядок",
    orderHistory: 'История заказов',
    outlet: 'Торговая точка',
    outlets: "Торговые точки",
    ownersOfSalons: "Владельцы салонов",
    participants: "Участники",
    passedSeminars: "Пройденных семинаров",
    password: "Пароль",
    passwordConfirm: "Подтвердите пароль",
    periodOfRegistration: 'Период регистрации',
    phoneFormat: "Формат телефона",
    phones: "Телефоны",
    price: "Цена",
    program: "Программа",
    quantity: "Количество",
    quarter: "Квартал",
    question: "Вопрос",
    questionsAndAnswers: "Вопросы и ответы",
    range: "Диапазон",
    readMore: 'Подробнее',
    recipients: "Получатели",
    region: 'Регион',
    regionByApplication: "Регион по заявкам",
    regionOnRequest: 'Регион по заявкам',
    regions: 'Регионы',
    regionsHeads: "Руководители регионов",
    regionsOfEducation: 'Регионы обучения',
    regionsOfTraining: "Регионы обучения",
    reject: "Отклонить",
    rejected: "Отклонено",
    resetAll: "Сбросить все",
    resetEverything: 'Сбросить все',
    resolutionOfTestsTo: 'Разрешение тестов всем',
    responsible: "responsible",
    responsiblePerson: 'Ответственное лицо',
    responsiblePersons: "Ответственные лица",
    responsibleSalesRepresentative: "Ответственный Торговый представитель",
    responsibleSt: "Ответственный СВ",
    responsibleSupervisor: "Ответственный Супервизор",
    responsibleTradingRepresentative: 'Ответственный Торговый представитель',
    role: "Роль",
    roles: "Роли",
    rr: 'РР',
    rro: "РРО",
    russiaKazakhstan: "Россия, Казахстан",
    salesManager: 'Руководитель продаж',
    salesManagers: "Руководители продаж",
    salesRepresentative: "Торговый представитель",
    salesRepresentatives: 'Торговые представители',
    salesRepresentetive: "Бизнес консультант",
    salon: "Салон",
    salonAdministrator: "Администратор салона",
    salonAdministrators: "Администраторы салонов",
    salonEmployees: "Сотрудники салонов",
    salonName: "Название салона",
    salonOwners: 'Владельцы салонов',
    salons: 'Салоны',
    salonsCount: 'Салонов',
    sample: "Шаблон",
    search: 'Поиск',
    selectTheSalons: "Выберите салоны",
    seminar: "Семинар",
    seminarTemplates: 'Шаблоны семинаров',
    seminarTitle: "Название семинара",
    seminars: 'Семинары',
    seminarsCompleted: "Пройдено семинаров",
    seminarsPassed: 'Пройдено семинаров',
    sen: "Сен",
    sep: 'Сен',
    service: "Услуга",
    settings: 'Настройки',
    settlements: "Населенные пункты",
    shipment: 'Отгрузка',
    shipmentMonth: "Месяц отгрузки",
    showFilters: 'Показать фильтры',
    siberia: "Сибирь",
    signUp: "Записаться",
    siteAdministrators: 'Администраторы сайта',
    sorting: "Сортировка",
    start: "Начало",
    status: 'Статус',
    stylists: 'Стилисты',
    stylistsCount: 'Стилистов',
    submitYourApplication: "Оставить заявку",
    successfulBlocking: "Успешная блокировка",
    successfulChange: "Успешное изменение",
    successfulConfirmation: "Успешное подтверждение",
    successfulUnlock: "Успешная разблокировка",
    superAdmin: "Суперадминистратор",
    superAdministrator: 'Суперадминистратор',
    supervisor1: "Супервайзер1",
    supervisor: 'Супервайзер',
    supervisors: "Супервайзеры",
    surname: "Фамилия",
    surnames: "Фамилии",
    target: "Цель",
    teacher: "Преподаватель",
    teachers: "Преподаватели",
    techno: "Технологи",
    technologistSupervisors: 'Супервайзеры технологов',
    technologists: 'Технологи',
    telephone: "Телефон",
    templateCatalogs: 'Категории шаблонов',
    templateCategories: 'Категории шаблонов',
    temporaryZone: "Временная зона",
    testManagement: "Управление тестами",
    tests: 'Тесты',
    text: "Текст",
    theAddressOfThe: 'Адрес проведения',
    theAreaOfResponsibility: 'Зона ответствености',
    theBeginningOfThe: "Начало трансляции",
    theChoiceOfRoles: "Выбор ролей",
    theCountryOfRegistration: 'Страна регистрации',
    theDate: "Дата",
    theDateOfThe: "Дата начала",
    theDateOfTheFirstSeminar: 'Дата первого семинара',
    theEnding: "Окончание",
    theHeadOfThe: "Руководитель региона",
    theLocalTime: "Местное время",
    theNameOfThe: "Название адреса",
    theNameOfTheSalon: 'Название салона',
    theOwnerOfThe: "Владелец салона",
    thePlayerCode: "Код плеера",
    theRegionOfTraining: "Регион обучения",
    theShops: "Магазины",
    timezone: "Часовой пояс",
    title: 'Название',
    toAccept: "Принять",
    topics: "Темы",
    tradePoint: "Торговая точка",
    tradeTurnover: "Товарооборот",
    trainingLeader: "Тренинг-лидер",
    trainingRegion: 'Регион обучения',
    turnover: 'Товарооборот',
    type: "Тип",
    typeOf: "Тип",
    unique: "Уникальных",
    unlock: "Разблокировать",
    ural: "Урал",
    users: "Пользователи",
    venueAddress: "Адрес проведения",
    version: "Версия",
    video: "Видео",
    videoCategories: 'Категории видео',
    virtual: "Виртуальная",
    waiting: 'Ожидает',
    warmId: 'WARM ID',
    webinar: "Вебинар",
    webinarCalendar: 'Календарь вебинаров',
    webinarParticipants: 'Участники вебинаров',
    webinars: 'Вебинары',
    webinarsTemplates: "Шаблоны вебинаров",
    worksRHDA: 'Работы RHDA',
    year: "Год",
    zoneOfResponsibility: 'Зона ответственности',
  },
};

module.exports = data.global
