const data = {
  global: {
    academyAdministrator: "Руководитель продаж",
    acceptedByMember: "Принято участником",
    additionalStatus: "Доп.статус",
    administrator: "Суперадминистратор",
    allowTestsForEveryone: "Разрешение тестов всем",
    answer: "Ответ",
    apply: "Применить",
    apr: "Апр",
    areaOfResponsibility: "Зона ответственности",
    attachFiles: "Прикрепите файлы",
    attachImages: "Прикрепите изображения",
    aug: "Авг",
    author: "Автор",
    availability: "Доступность",
    avatar: "Аватар",
    awaiting: "Ожидает",
    block: "Блокировать",
    buy: "Купить",
    canCreateWebinars: "Может создавать вебинары",
    channel: "Канал",
    clientWithoutDMS: "Клиент без ДМС",
    close: "Закрыть",
    clubSKPLevel: "Уровень Club SKP",
    comment: "Комментарий",
    confirm: "Подтвердить",
    countryOfRegistration: "Страна регистрации",
    creator: "Преподаватель",
    crmManager: "Семинар",
    dateAndTime: "Дата и время",
    dateOfRegistration: "Дата регистрации",
    dateOfTheFirst: "Дата первого семинара",
    dec: "Дек",
    dependentSeminars: "Зависимые семинары",
    detailedInformation: "Подробная информация",
    didNotHave: "Не было",
    download: "Скачать",
    duration: "Длительность",
    "duration(min)": "Продолжительность (мин)",
    entity: "Преподаватель (спикер)",
    expirationDate: "Дата окончания",
    externalRoles: "Внешние роли",
    feb: "Фев",
    file: "Файл",
    filters: "Фильтры",
    further: "Далее",
    headOfRegionEducation: "Администратор",
    headOfSales: "Создатель",
    hide: "Скрыть",
    highlight: "Подсветить",
    image: "Изображение",
    inactive: "Неактивный",
    individuals: "Выпускники",
    indolaLoyaltyLevel: "Уровень Indola Loyalty",
    internalRoles: "Внутренние роли",
    isCopyright: "Является авторским",
    jan: "Янв",
    july: "Июль",
    june: "Июнь",
    "lecturer(speaker)": "Индивидуалы",
    limitedAccess: "Ограниченный доступ",
    linkToVimeo: "Ссылка на vimeo",
    location: "Место проведения",
    mail: "Почта",
    mar: "Мар",
    may: "Май",
    mediaFiles: "Медиа-файлы",
    middleName: "Отчество",
    more: "Подробнее",
    name: "Имя",
    ncaThreshold: "Порог NCA",
    nomination: "Номинация",
    nov: "Ноя",
    oct: "Окт",
    order: "Порядок",
    passedSeminars: "Пройденных семинаров",
    phoneFormat: "Формат телефона",
    question: "Вопрос",
    questionsAndAnswers: "Вопросы и ответы",
    regionByApplication: "Регион по заявкам",
    reject: "Отклонить",
    rejected: "Отклонено",
    resetAll: "Сбросить все",
    responsiblePersons: "Ответственные лица",
    responsibleSalesRepresentative: "Ответственный Торговый представитель",
    responsibleSupervisor: "Ответственный Супервизор",
    role: "Роль",
    roles: "Администратор салона",
    salesRepresentetive: "Руководитель региона обучения",
    salonAdministrator: "Торговая точка",
    salonName: "Название салона",
    seminar: "Юридическое лицо",
    seminarTitle: "Название семинара",
    seminarsCompleted: "Пройдено семинаров",
    sen: "Сен",
    service: "Услуга",
    shipmentMonth: "Месяц отгрузки",
    signUp: "Записаться",
    sorting: "Сортировка",
    start: "Начало",
    submitYourApplication: "Оставить заявку",
    successfulBlocking: "Успешная блокировка",
    successfulChange: "Успешное изменение",
    successfulConfirmation: "Успешное подтверждение",
    successfulUnlock: "Успешная разблокировка",
    superAdmin: "Администратор Академии",
    surname: "Фамилия",
    teacher: "Тренинг-лидер",
    text: "Текст",
    theDate: "Дата",
    theEnding: "Окончание",
    theLocalTime: "Местное время",
    timezone: "Часовой пояс",
    toAccept: "Принять",
    tradePoint: "Бизнес консультант",
    tradeTurnover: "Товарооборот",
    trainingLeader: "CRM-менеджер",
    unlock: "Разблокировать",
    venueAddress: "Адрес проведения",
    version: "Версия",
    video: "Видео",
    virtual: "Виртуальная",
  },
};

export default data